[[variables]]
name = "q"
dim = 2
init = [0.0, 0.0]

[[terms]]

[terms.expr]
type = "sub"
name = "q_minus_target"

[terms.expr.a]
type = "get_var"
var = "q"

[terms.expr.b]
type = "const"
var = "q"
value = [0.5, -1.2]

[terms.cost]
type = "l2"
