[time]
N = 10
dt = 0.1

[trajectory]
   type = "bspline"
   var = "p"
   q_dim = 2
   degree = 3
   num_ctrl_points = 4

[[variables]]
name = "p"
dim = 8
init = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

[[terms]]
    [terms.expr]
    type = "sub"

    [terms.expr.a]
    type = "stack"
    name = "ee_pos_traj"

    [terms.expr.a.range]
    k0 = 0
    k1 = 10

    [terms.expr.a.inner]
    type = "get_state"
    name = "ee_pos"

    [terms.expr.a.inner.key]
    owner_type = "link"
    owner_name = "ee"
    dtype = "kinematics"
    field = "pos"

    [terms.expr.a.inner.jac]
    var = "p"

    [terms.expr.b]
    type = "const"
    var = "p"
    name = "target_pos_traj"
    value = [
      2.0, 0.0, 0.0,
      1.88, 0.16, 0.0,
      1.76, 0.32, 0.0,
      1.64, 0.48, 0.0,
      1.52, 0.64, 0.0,
      1.40, 0.80, 0.0,
      1.28, 0.88, 0.0,
      1.16, 0.96, 0.0,
      1.04, 1.04, 0.0,
      0.92, 1.12, 0.0,
      0.80, 1.20, 0.0
    ]

    [terms.cost]
    type = "l2"

[[terms]]
    [terms.expr]
    type = "time_diff"
    name = "traj_smooth"
    segment_dim = 2

    [terms.expr.base]
    type = "get_traj_var"
    name = "q_traj"
    var = "p"

    [terms.cost]
    type = "scalar_weight"
    w = 1e-3
