[time]
N = 10
dt = 0.1

[trajectory]
type = "bspline"
var = "p"
q_dim = 2
degree = 4
num_ctrl_points = 6

[[variables]]
name = "p"
dim = 12
init = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

[[terms]]
  [terms.constraint]
  kind = "eq"

  [terms.expr]
  type = "sub"
  name = "task_init_joint_q"

  [terms.expr.a]
  type = "get_state"
  name = "joint_q_init"

  [terms.expr.a.key]
  k = 0
  owner_type = "total_joint"
  owner_name = "robot"
  dtype = "joint"
  field = "q"

  [terms.expr.a.jac]
  var = "p"

  [terms.expr.b]
  type = "const"
  var = "p"
  name = "target_q_init"
  value = [1.57, 0.0]

  [terms.cost]
  type = "scalar_weight"
  w = 1.0

[[terms]]
  [terms.constraint]
  kind = "eq"

  [terms.expr]
  type = "sub"
  name = "task_terminal_joint_q"

  [terms.expr.a]
  type = "get_state"
  name = "joint_q_terminal"

  [terms.expr.a.key]
  k = 10
  owner_type = "total_joint"
  owner_name = "robot"
  dtype = "joint"
  field = "q"

  [terms.expr.a.jac]
  var = "p"

  [terms.expr.b]
  type = "const"
  var = "p"
  name = "target_q_terminal"
  value = [-1.57, 0.0]

  [terms.cost]
  type = "scalar_weight"
  w = 1.0

[[terms]]
  is_constraint = true

  [terms.attrs]
  group = "joint_limit"

  [terms.constraint]
  kind = "ineq"

  [terms.expr]
  type = "hinge"
  name = "q_upper_limit_hinge"

  [terms.expr.base]
  type = "sub"

  [terms.expr.base.a]
  type = "get_traj_var"
  name = "q_traj_for_upper"
  var = "p"

  [terms.expr.base.b]
  type = "const_repeat"
  var = "p"
  name = "q_max_traj"
  value = [3.141592653589793, 3.141592653589793]

  [terms.cost]
  type = "scalar_weight"
  w = 1e-2

[[terms]]
  is_constraint = true

  [terms.attrs]
  group = "joint_limit"

  [terms.constraint]
  kind = "ineq"

  [terms.expr]
  type = "hinge"
  name = "q_lower_limit_hinge"

  [terms.expr.base]
  type = "sub"

  [terms.expr.base.a]
  type = "const_repeat"
  var = "p"
  name = "q_min_traj"
  value = [-3.141592653589793, -3.141592653589793]

  [terms.expr.base.b]
  type = "get_traj_var"
  name = "q_traj_for_lower"
  var = "p"

  [terms.cost]
  type = "scalar_weight"
  w = 1e-2

[[terms]]
  [terms.constraint]
  kind = "eq"

  [terms.expr]
  type = "sub"
  name = "task_init_joint_qdot"

  [terms.expr.a]
  type = "get_traj_var"
  name = "joint_qdot_init"
  var = "p"
  derivative_order = 1
  derivative_wrt = "time"
  k = 0

  [terms.expr.b]
  type = "const"
  var = "p"
  name = "target_qdot_init"
  value = [0.0, 0.0]

  [terms.cost]
  type = "scalar_weight"
  w = 1.0

[[terms]]
  [terms.constraint]
  kind = "eq"

  [terms.expr]
  type = "sub"
  name = "task_terminal_joint_qdot"

  [terms.expr.a]
  type = "get_traj_var"
  name = "joint_qdot_terminal"
  var = "p"
  derivative_order = 1
  derivative_wrt = "time"
  k = 10

  [terms.expr.b]
  type = "const"
  var = "p"
  name = "target_qdot_terminal"
  value = [0.0, 0.0]

  [terms.cost]
  type = "scalar_weight"
  w = 1.0

[[terms]]
  [terms.expr]
  type = "get_traj_var"
  name = "qdot_traj_regularization"
  var = "p"
  derivative_order = 1
  derivative_wrt = "time"

  [terms.cost]
  type = "scalar_weight"
  w = 1e-3

[[terms]]
  [terms.expr]
  type = "stack"
  name = "tau_traj_regularization"

  [terms.expr.range]
  k0 = 0
  k1 = 10

  [terms.expr.inner]
  type = "get_state"
  name = "tau_k"

  [terms.expr.inner.key]
  owner_type = "total_joint"
  owner_name = "robot"
  dtype = "dynamics"
  field = "tau"

  [terms.expr.inner.jac]
  var = "p"

  [terms.cost]
  type = "scalar_weight"
  w = 1e-5

[[terms]]
  [terms.expr]
  type = "stack"
  name = "dtau_traj_regularization"

  [terms.expr.range]
  k0 = 0
  k1 = 10

  [terms.expr.inner]
  type = "get_state"
  name = "dtau_k"

  [terms.expr.inner.key]
  owner_type = "total_joint"
  owner_name = "robot"
  dtype = "dynamics"
  field = "tau_diff"

  [terms.expr.inner.jac]
  var = "p"

  [terms.cost]
  type = "scalar_weight"
  w = 1e-5

