[[variables]]
name = "x"
dim = 1
init = [0.0]

[[terms]]
  [terms.expr]
  type = "sub"
  name = "track_pos"

  [terms.expr.a]
  type = "get_var"
  var = "x"

  [terms.expr.b]
  type = "const"
  var = "x"
  name = "target_pos"
  value = [1.0]

  [terms.cost]
  type = "scalar_weight"
  w = 3.0

[[terms]]
  [terms.expr]
  type = "sub"
  name = "track_neg"

  [terms.expr.a]
  type = "get_var"
  var = "x"

  [terms.expr.b]
  type = "const"
  var = "x"
  name = "target_neg"
  value = [-1.0]

  [terms.cost]
  type = "scalar_weight"
  w = 1.0
