"""Rei package entrypoint.

The canonical API is exposed under domain namespaces:
`rei.optimize`, `rei.equations`, and `rei.flow`.
"""

from __future__ import annotations

from . import core, equations, flow, optimize, optimize_backends
from .equations import (
    EquationPoint,
    EvaluateEquation,
    LinearizedEquation,
    OperatorEquation,
    RuntimeStationaritySource,
    SimplexMinNormProblem,
    StationaritySource,
    StationarityTermContribution,
    as_linear_equation_problem,
    build_reference_simplex_init,
    build_stationarity_gradient_matrix,
    filter_stationarity_contributions,
    normalize_simplex_nonnegative,
    select_active_stationarity_indices,
    term_constraint_kind,
    solve_projected_linearized_min_norm,
    solve_simplex_min_norm,
)
from .flow import (
    RuntimeIdentityProjector,
    as_constraint_problem,
    as_project_problem,
)
from .core import (
    Profiler,
    SolveOutcome,
    SolveStats,
    TimingReport,
    TimingSpan,
    ensure_profiler,
)
from .optimize import (
    ConstraintProblem,
    EvaluateProblem,
    KKTCheckResult,
    LinearizedProblem,
    NLSProblem,
    NLSRuntime,
    NLSRuntimeConstraintProblem,
    NLSRuntimeLinearProblem,
    OperatorProblem,
    ProblemPoint,
    ProjectProblem,
    as_linearized_problem,
    build_term_gradient_matrix,
    build_term_gradient_matrix_from_stacked,
    build_term_gradient_matrix_from_terms,
    check_kkt_conditions,
    check_kkt_residuals,
    collect_named_expr_values,
    collect_plot_series_from_term_attrs,
    compile_nls_problem,
    format_timing_report,
    format_solve_report,
    get_named_expr_value,
    load_problem_toml,
    nls,
    plot_term_attrs,
    solve,
    solve_cyipopt_minimize,
    solve_gauss_newton,
    solve_liteopt_gd,
    solve_scipy_minimize,
    split_terms_by_component,
)

__all__ = [
    "core",
    "optimize",
    "equations",
    "flow",
    "optimize_backends",
    "nls",
    "solve",
    "solve_gauss_newton",
    "solve_scipy_minimize",
    "solve_cyipopt_minimize",
    "solve_liteopt_gd",
    "compile_nls_problem",
    "load_problem_toml",
    "ProblemPoint",
    "EvaluateProblem",
    "LinearizedProblem",
    "OperatorProblem",
    "ProjectProblem",
    "ConstraintProblem",
    "NLSRuntimeLinearProblem",
    "NLSRuntimeConstraintProblem",
    "as_linearized_problem",
    "NLSProblem",
    "NLSRuntime",
    "KKTCheckResult",
    "check_kkt_conditions",
    "check_kkt_residuals",
    "format_solve_report",
    "format_timing_report",
    "collect_named_expr_values",
    "get_named_expr_value",
    "collect_plot_series_from_term_attrs",
    "plot_term_attrs",
    "build_term_gradient_matrix",
    "build_term_gradient_matrix_from_stacked",
    "build_term_gradient_matrix_from_terms",
    "SimplexMinNormProblem",
    "solve_projected_linearized_min_norm",
    "solve_simplex_min_norm",
    "StationaritySource",
    "StationarityTermContribution",
    "normalize_simplex_nonnegative",
    "term_constraint_kind",
    "filter_stationarity_contributions",
    "build_stationarity_gradient_matrix",
    "select_active_stationarity_indices",
    "build_reference_simplex_init",
    "RuntimeStationaritySource",
    "EquationPoint",
    "EvaluateEquation",
    "LinearizedEquation",
    "OperatorEquation",
    "as_linear_equation_problem",
    "RuntimeIdentityProjector",
    "as_constraint_problem",
    "as_project_problem",
    "split_terms_by_component",
    "SolveStats",
    "SolveOutcome",
    "TimingSpan",
    "TimingReport",
    "Profiler",
    "ensure_profiler",
]
