[time]
N = 200
dt = 0.01

[trajectory]
type = "bspline"
var = "p"
degree = 5
num_ctrl_points = 50

[opt_vals.trajectory_params.init]
fill = 0.0

[[terms]]
name = "q_init"
kind = "eq"
enforce = "nullspace"
weight = 100.0
quantity = "joint_angles"
at = 0
target = { fill = 1.57 }
plot = "joint_q"

[[terms]]
name = "q_terminal"
kind = "eq"
enforce = "nullspace"
weight = 100.0
quantity = "joint_angles"
at = "last"
target = { fill = -1.57 }

[[terms]]
name = "qdot_init"
kind = "eq"
enforce = "nullspace"
weight = 100.0
quantity = "joint_velocities"
at = 0
target = { fill = 0.0 }

[[terms]]
name = "qdot_terminal"
kind = "eq"
enforce = "nullspace"
weight = 100.0
quantity = "joint_velocities"
at = "last"
target = { fill = 0.0 }

[[terms]]
name = "joint_q_bounds"
kind = "ineq"
weight = 1e5
quantity = "joint_angles"
bounds = { lower = { fill = -3.14159 }, upper = { fill = 3.14159 } }

[[terms]]
name = "qdot_traj_regularization"
weight = 1e-4
quantity = "joint_velocities"

[[terms]]
name = "qddot_traj_regularization"
weight = 1e-4
quantity = "joint_accelerations"

[[terms]]
name = "torque_traj_regularization"
weight = 1e-10
plot = { name = "joint_torque", stride = 50 }
quantity = "joint_torques"
stride = 50
