[time]
N = 200
dt = 0.01

[trajectory]
type = "bspline"
var = "p"
degree = 5
num_ctrl_points = 50

[opt_vals.trajectory_params.init]
fill = 0.0

[[terms]]
name = "q_init"
kind = "eq"
weight = 100.0
state = "coord.total_joint.robot.q"
var = "trajectory_params"
at = 0
target = { fill = 1.57 }
attrs = { nullspace_eq = true, plot = { type = "state_traj", name = "joint_q" } }

[[terms]]
name = "q_terminal"
kind = "eq"
weight = 100.0
state = "coord.total_joint.robot.q"
var = "trajectory_params"
at = "last"
target = { fill = -1.57 }
attrs = { nullspace_eq = true }

[[terms]]
name = "qdot_init"
kind = "eq"
weight = 100.0
quantity = "joint_velocities"
at = 0
target = { fill = 0.0 }
attrs = { nullspace_eq = true }

[[terms]]
name = "qdot_terminal"
kind = "eq"
weight = 100.0
quantity = "joint_velocities"
at = "last"
target = { fill = 0.0 }
attrs = { nullspace_eq = true }

[[terms]]
name = "joint_q_upper_violation"
kind = "ineq"
weight = 1e5
residual = { op = "hinge", base = { op = "sub", name = "joint_q_minus_qmax", a = { quantity = "joint_angles" }, b = { const_repeat = { fill = 3.14159 }, name = "joint_q_max", var = "trajectory_params" } } }

[[terms]]
name = "joint_q_lower_violation"
kind = "ineq"
weight = 1e5
residual = { op = "hinge", base = { op = "sub", name = "joint_qmin_minus_q", a = { const_repeat = { fill = -3.14159 }, name = "joint_q_min", var = "trajectory_params" }, b = { quantity = "joint_angles" } } }

[[terms]]
name = "qdot_traj_regularization"
weight = 1e-4
quantity = "joint_velocities"

[[terms]]
name = "qddot_traj_regularization"
weight = 1e-4
quantity = "joint_accelerations"
